README.md
pkg/cmd/exec.go
pkg/cmd/post.go
pkg/comment/mock.go
pkg/option/exec.go
pkg/option/post.go

Close #83 
Add an option `-dry-run` to the commands `post` and `exec`.
When the option is set, the comment isn't posted to GitHub but outputted to the standard error output.
ex.
```
$ github-comment post -dry-run -template hello
[github-comment][DRYRUN] Comment to suzuki-shunsuke/github-comment sha1:xxx issue:10
[github-comment][DRYRUN] hello
```

feat: support dry run

---

README.md
pkg/api/exec.go
pkg/api/init.go
pkg/api/post.go
pkg/api/post_internal_test.go
pkg/comment/comment.go
pkg/config/config.go
pkg/option/exec.go
pkg/option/post.go

Close #124 
When the comment is too long, it is failed to post a comment due to GitHub API's validation.
```json
{
"message": "Validation Failed",
"errors": [
{
"resource": "IssueComment",
"code": "unprocessable",
"field": "data",
"message": "Body is too long (maximum is 65536 characters)"
}
],
"documentation_url": "https://docs.github.com/rest/reference/issues#create-an-issue-comment"
}
```
If a comment includes the long command standard output, you may encounter the error.
github-comment supports to post a substitute comment in that case.
When it is failed to post a comment of `template`, github-comment posts a comment of `template_for_too_long` instead of `template`.
ex.
```yaml
post:
hello:
template: too long comment
template_for_too_long: comment is too long
exec:
hello:
- when: …
```

feat: post a substitute comment when it is failed to post a too long comment

---

.github-comment.yml
pkg/config/config.go

https://app.circleci.com/pipelines/github/suzuki-shunsuke/github-comment/70/workflows/9c8ce42b-08b1-43e5-965a-3eedf8170089/jobs/65
```
+ go run ./cmd/github-comment post --dry-run -k hello
invalid config. post config should be string or map[string]intterface{}: map[template:$Hello: {{Env "HELLO"}} {{ "hello!" | upper | repeat 5 }}
]
exit status 1
```

ci: fix unmarshaling of PostConfig

---

pkg/comment/comment.go

fix: don't call fmt.Errorf if err is nil

---

README.md
pkg/template/template.go

The following comment is escaped to `&lt;` by Go's html/template.
```
template: |
<
```
To comment `<`, use the function `AvoidHTMLEscape` like this.
```
template: |
{{ "<" | AvoidHTMLEscape }}
```

feat: add a template function AvoidHTMLEscape

---

pkg/template/template.go

If CI service isn't detected, the template "link" isn't defined.
```
github-comment error: render a comment template: render a template with params: html/template:comment:2:169: no such template "link"
```
Set an empty string to the template "link" if CI service isn't detected.

fix: define the template "link" always

---

README.md
pkg/api/post.go
pkg/api/post_internal_test.go
pkg/cmd/post.go
pkg/option/post.go

Close #169
```
echo hello | github-comment post
```
From v2.0.0, in case of the above command, the standard input will be ignored and the `default` template will be used.
```
echo hello | github-comment post -stdin-template
```

fix: add the option `-stdin-template` to post command

---

pkg/template/template.go

If the content of `.CombinedOutput` is Markdown-like,
it will be parsed as markdown and the posted comment will be ugly.

Don't use <pre><code> tags in hidden_combined_output

---

README.md
pkg/api/exec.go
pkg/api/post.go
pkg/template/template.go

Follow up #182 
If `.JoinCommand` includes \`\`\`,
```
<pre><code>$ {{.JoinCommand | AvoidHTMLEscape}}</pre></code>
```
Otherwise,
<pre><code>```
$ {{.JoinCommand | AvoidHTMLEscape}}
```</pre></code>
If `.CombinedOutput` includes \`\`\` ,
```
<details><pre><code>{{.CombinedOutput | AvoidHTMLEscape}}</code></pre></details>
```
Otherwise,
<pre><code>&lt;details&gt;
```
{{.CombinedOutput | AvoidHTMLEscape}}
```
&lt;/details&gt;</pre></code>

fix: fix builtin template join_command and hidden_combined_output

---

pkg/api/post.go

Follow up #189 
GitHub Actions's GITHUB_TOKEN secret doesn't have a permission to get an authenticated user.
So if `login` is empty, we give up filtering comments by login.

fix: don't filter commits by login when login is empty

---

pkg/api/post.go

fix: ignore error to get an authenticated user

---

pkg/api/comment.go
pkg/api/exec.go
pkg/api/hide.go
pkg/api/post.go
pkg/api/post_internal_test.go
pkg/cmd/app.go
pkg/cmd/hide.go
pkg/config/config.go
pkg/option/hide.go
pkg/platform/platform.go

#205 
* Add a command `hide`, which hides old comments
```
$ github-comment hide
```
ex.
```yaml
---
hide:
plan: 'Comment.HasMeta && (Comment.Meta.SHA1 != Commit.SHA1 || Comment.Meta.Vars.target == "foo")'
```
```
$ github-comment hide -k plan
```
* a HTML comment is embedded to a comment
* remove the feature to hide comments in `post` and `exec` command
ex.
```
```
* SHA1
* TemplateKey
* Vars
* JobID (optional)
* JobName (optional)
* WorkflowName (optional)
These meta data can be referred in hide condition as `Comment.Meta`.
We think the current specification to hide comments has some problems.
It is inefficient to get comments and extract hidden comments from them several times.
So instead of hiding comments in `post` and `exec` command, we should call `hide` command in the begging of …

feat: add a command "hide" and embed meta data to comment

---

README.md
pkg/platform/platform.go

https://github.com/suzuki-shunsuke/ci-info
The environment variable `CI_INFO_PR_NUMBER` is set by [ci-info](https://github.com/suzuki-shunsuke/ci-info) by default. 
If the pull request number can't be gotten from platform's built-in environment variables but `CI_INFO_PR_NUMBER` is set, github-comment uses `CI_INFO_PR_NUMBER`.

feat: get the pull request number from CI_INFO_PR_NUMBER

---

go.mod
go.sum
pkg/api/comment.go
pkg/api/hide.go

It failed to hide comments with metadata `Comment.Meta` because it is always an empty map.

fix: Comment.Meta is empty

---

README.md
pkg/api/hide.go
pkg/cmd/app.go
pkg/cmd/hide.go
pkg/option/hide.go

Support to specify the condition with `-condition` option.
```
$ github-comment hide -condition 'Comment.Body contains "foo"'
```

feat: add hide condition option

---

pkg/cmd/app.go
pkg/cmd/exec.go
pkg/cmd/post.go
pkg/comment/comment.go

Close #277
```
$ github-comment post -var-file content:foo.txt
```
```
$ github-comment exec -var-file content:foo.txt -- echo hello
```

feat: add the -var-file option to the post command

---

README.md
pkg/api/exec.go
pkg/api/post.go
pkg/config/config.go
pkg/option/post.go

BREAKING CHANGE: no variable becomes embedded in comment by default
github-comment embedds the metadata into the comment to hide the comment by the metadata.
With github-comment v3, all variables are embedded into the comment, but sometimes this behaviour is undesirable.
With github-comment v4, only variables specified by `embedded_var_names` are embedded into the comment.
```yaml
post:
hello:
template: "Hello {{.Vars.name}}"
embedded_var_names:
- name
exec:
hello:
- when: true
template: "Hello {{.Vars.name}}"
embedded_var_names:
- name
```

feat: add embeded_var_names to post and exec config

---

go.mod
go.sum
pkg/platform/google_cloud_build.go
pkg/platform/platform.go
pkg/template/template.go

Please set the environment variable `GOOGLE_CLOUD_BUILD`.
```sh
GOOGLE_CLOUD_BUILD=true
```
And please set the following environment variables using [substitutions](https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values).
* `COMMIT_SHA`
* `BUILD_ID`
* `PROJECT_ID`
* `_PR_NUMBER`
* `_REGION`
Please specify the repository owner and name in `github-comment.yaml`.
e.g.
github-comment.yaml
```yaml
base:
org: suzuki-shunsuke
repo: github-comment
```

feat: support Google Cloud Build

---

pkg/template/template.go

Follow up https://github.com/suzuki-shunsuke/github-comment/pull/867
Affected versions:
- v5.1.0

fix: remove double quotes from JoinCommand

---

pkg/cmd/app.go

- `-org`: `GITHUB_COMMENT_REPO_ORG`, `GHCMT_REPO_ORG`
- `-repo`: `GITHUB_COMMENT_REPO_NAME`, `GHCMT_REPO_NAME`
- `-sha1`: `GITHUB_COMMENT_SHA1`, `GHCMT_SHA1`
- `-config`: `GITHUB_COMMENT_CONFIG`, `GHCMT_CONFIG`
- `-pr`: `GITHUB_COMMENT_PR_NUMBER`, `GHCMT_PR_NUMBER`

feat: support passing some command line arguments via environment variables

---

pkg/github/comment.go

Based on the following discussion, I added a waring log when github-comment uses `BodyForTooLong`.
- https://github.com/suzuki-shunsuke/github-comment/discussions/986
If `BodyForTooLong` is unset, the body of comment will be empty without any logs.
By adding the log, developers can debug their comment easliy.

chore: add warning comment for body too long

---

go.mod
go.sum
pkg/execute/execute.go

go-timeout was deprecated.
https://github.com/suzuki-shunsuke/go-timeout#warning-deprecated-go-120-has-supported-the-feature-officially

refactor: replace suzuki-shunsuke/go-timeout to exec.CommandContext, Cmd.Cancel, and Cmd.WaitDelay

---

pkg/api/exec.go

- Link to the issue: https://github.com/suzuki-shunsuke/github-comment/issues/1581
- This repository enables `Require signed commits`, so all commits must be signed
A panic occurred when I executed `github-comment exec` without args.
```bash
$ github-comment exec --
panic: runtime error: slice bounds out of range [1:0]
goroutine 1 [running]:
github.com/suzuki-shunsuke/github-comment/v6/pkg/api.(*ExecController).Exec(0x140001cf358, {0x1007b3138, 0x14000139300}, 0x1400011a7e0)
/home/runner/work/github-comment/github-comment/pkg/api/exec.go:72 +0xb94
github.com/suzuki-shunsuke/github-comment/v6/pkg/cmd.(*Runner).execAction(0x14000139340, 0x14000139600)
/home/runner/work/github-comment/github-comment/pkg/cmd/exec.go:123 +0x5bc
github.com/urfave/cli/v2.(*Command).Run(0x140001a0420, …
```

fix: added check of exists args in `github-comment exec` command
