suzuki-shunsuke/github-comment

pkg/api/exec.go, pkg/api/post.go, pkg/cmd/exec.go, pkg/cmd/post.go, pkg/option/exec.go, pkg/option/post.go
=> feat: support the flag "-var"

pkg/api/exec.go, pkg/api/post.go, pkg/api/post_internal_test.go, pkg/config/config.go
=> feat: support to configure some parameters with the configuration file

.drone.yml, .gitignore, scripts/test-code-climate.sh
=> ci: replace codecov to code climate

README.md
=> docs: replace codecov's status badge to code climate's status badge

pkg/api/exec.go, pkg/cmd/exec.go
=> feat: exec command supports the -template flag same as post command

pkg/api/exec.go, pkg/config/config.go
=> fix: make config file optional

pkg/api/exec.go, pkg/api/post.go, pkg/config/config.go, pkg/template/template.go
=> feat: add templates in the configuration file

pkg/api/init.go, pkg/cmd/app.go, pkg/cmd/init.go, pkg/fsys/fsys.go
=> feat: support init command

pkg/option/post.go
=> feat: support the parameter completion on Drone

pkg/api/exec.go
Close #79 
Command
```
echo foo
```
Template
```
{{.Command}}
{{.JoinCommand}}
```
Result
```
/usr/local/opt/coreutils/libexec/gnubin/echo foo
echo foo
```
=> feat: add JoinCommand

pkg/api/exec.go, pkg/api/post.go, pkg/cmd/exec.go, pkg/cmd/post.go, pkg/option/exec.go, pkg/option/post.go, pkg/platform/circleci.go, pkg/platform/drone.go, pkg/platform/github_actions.go, pkg/platform/platform.go
=> feat: support GitHub Actions

README.md
https://techblog.szksh.cloud/github-comment/
=> docs: add a link to blog

README.md, pkg/platform/codebuild.go, pkg/platform/codebuild_internal_test.go, pkg/platform/platform.go
=> feat: support to complate parameters on CodeBuild

pkg/api/exec.go, pkg/api/post.go
=> fix: initialize the map before assignment to prevent panic

pkg/api/exec.go
=> fix: output error

.drone.yml, .github-comment.yml, .gitignore, pkg/platform/drone.go, scripts/test-dry-run.sh
* ci: run `dry run` in CI for testing
* fix: fix the Drone's environment variable `DRONE_COMMIT_SHA1` to `DRONE_COMMIT_SHA`
=> ci: add dry run

.circleci/config.yml, .github/workflows/test.yml
=> ci: run `dry run` on CircleCI and GitHub Actions for testing

pkg/cmd/exec.go, pkg/cmd/post.go, pkg/option/exec.go, pkg/option/post.go
Close #115 
* add the configuration option `skip_no_token`
* test
* update README
=> feat: support "--skip-no-token"

README.md, pkg/api/exec.go, pkg/api/init.go, pkg/api/post.go, pkg/api/post_internal_test.go, pkg/cmd/exec.go, pkg/cmd/post.go, pkg/config/config.go
=> feat: add the configuration option `skip_no_token`

.github-comment.yml, README.md, go.mod, go.sum, pkg/template/template.go
http://masterminds.github.io/sprig/
Close #128
=> feat: add sprig as template functions

README.md, pkg/api/exec.go, pkg/cmd/exec.go, pkg/cmd/post.go, pkg/comment/mock.go, pkg/config/config.go, pkg/option/exec.go, pkg/option/post.go
=> feat: add the silent option

README.md, pkg/api/exec.go, pkg/cmd/exec.go, pkg/cmd/post.go, pkg/option/exec.go
=> feat: support to skip comment

pkg/api/exec.go
=> fix: fix handling err

pkg/api/exec.go, pkg/api/post.go
=> fix(exec): set template key

pkg/api/exec.go, pkg/api/post.go
=> fix: post a comment even if it failed to list hidden comments

README.md, pkg/api/exec.go, pkg/api/post.go, pkg/comment/comment.go, pkg/comment/mutate.go, pkg/config/config.go, pkg/option/exec.go, pkg/option/post.go
=> fix: rename "minimize" to "hide_old_comment"

pkg/api/hide.go
* fix: fix the parameter of the expression to hide comments
* feat: output logs about comment hidden
=> fix: fix hide command

pkg/option/hide.go, pkg/option/post.go
* validate whether the pull request number isn't set in `hide` command
=> fix: fix the validation of pull request number

pkg/api/hide.go
=> fix: validate hide parameters

go.mod, go.sum, pkg/api/comment.go
https://github.com/suzuki-shunsuke/github-comment-metadata
=> refactor: use github-comment-metadata

pkg/config/config.go
bdb6808d403ce117a7c2d4c2b534acc6f796130b
=> refactor: remove unused field

README.md, pkg/cmd/exec.go, pkg/cmd/hide.go, pkg/cmd/post.go, pkg/config/complement.go, pkg/domain/complement.go, pkg/platform/generic.go, pkg/platform/platform.go
=> feat: add vars to complement

.drone.yml, .github/workflows/test.yml, pkg/option/hide.go
Follow up #245 341ee16f8cc7e05a7120132697af767701894113
=> fix(hide): fix validation of hide command

pkg/platform/platform.go
=> fix: ignore negative pr number

pkg/signal/signal.go
しょうもない PR を送りつけてすみません。CI で動かす CLI ツールを作る参考にしたいなと思って眺めていたら気づいてしまいました
（もしテンプレートのリポジトリがあるようでしたらそちらに出すべきですが、パッと見当たらなかったので元々見ていたリポジトリに投げています :raised_hands: ）
=> fix: fix a typo "sinal"

github-comment.yaml, pkg/api/post.go, pkg/cmd/app.go, pkg/cmd/post.go, pkg/comment/comment.go, pkg/config/config.go, pkg/option/post.go, scripts/test-dry-run.sh
Draft implementation of. https://github.com/suzuki-shunsuke/github-comment/issues/473
Tested below ⬇️ with the following test case : 
```bash
HELLO=test go run ./cmd/github-comment/main.go post --org suzuki-shunsuke --repo github-comment --pr 474 -k hello -u 'Comment.HasMeta && Comment.Meta.TemplateKey == "hello"'
HELLO=test2 go run ./cmd/github-comment/main.go post --org suzuki-shunsuke --repo github-comment --pr 474 -k hello -u 'Comment.HasMeta && Comment.Meta.TemplateKey == "hello"' 
```
=> Feat - Add post update condition

pkg/api/post.go, pkg/api/post_internal_test.go, pkg/comment/comment.go
Follow up #474
* Refactoring
* Ignore minimized comments and other users' comments
=> fix: fix updating post comments

pkg/api/hide.go
=> fix(hide): support vars in configuration file

.github/workflows/test.yaml
Reverts suzuki-shunsuke/github-comment#777
It didn't work well.
=> Revert "ci: test renovate-enable-automerge-workflow"

pkg/template/template.go
https://github.com/suzuki-shunsuke/github-comment/issues/864
=> feat: add the template function WrapCode and omit too long text in hidden_combined_output

pkg/template/template.go
Reverts suzuki-shunsuke/github-comment#865
=> Revert "fix: remove Env template function for security"

pkg/template/template.go
Reverts suzuki-shunsuke/github-comment#893
=> Revert "Revert "fix: remove Env template function for security""

pkg/fsys/fsys.go
=> fix: fix the file permission of github-comment.yaml created by github-comment init

.github/workflows/test-main.yaml, .github/workflows/test.yaml, .github/workflows/wc-enable-auto-merge.yaml
https://github.com/suzuki-shunsuke/batch-bulk-ghatm/issues/1
=> ci: set timeout-minutes using ghatm

go.mod, go.sum
=> feat: post comments to pull request in case of merge_group event

pkg/cmd/post.go
=> feat: get GitHub API endpoints from environment variables

go.mod, go.sum, pkg/api/exec.go, pkg/cmd/app.go, pkg/cmd/exec.go, pkg/option/exec.go
=> feat(exec): support the option -out

.github/DISCUSSION_TEMPLATE/deprecated-question-and-answer.yml
=> chore: deprecate Question and Answer

.github/workflows/close-discussion.yaml
https://github.com/suzuki-shunsuke/close-discussion-action
=> ci: add a workflow to close the discussion

.github/workflows/test-main.yaml, .github/workflows/test.yaml
https://github.com/suzuki-shunsuke/batch-bulk-disable-checkout-persist-credentials/issues/1
=> ci: disable actions/checkout's persist-credentials using disable-checkout-persist-credentials

pkg/api/post.go, pkg/github/comment.go, pkg/option/post.go
- Link to the issue:
- This repository enables `Require signed commits`, so all commits must be signed
SSIA. This member of struct isn't used.
=> chore: remove unused option
